### ISSUE TITLE
Creat data.txt file to save requiredment data from .xml or .json file

### ISSUE THREAD

**Issue by hoanglonginthehus** [lanhtruonggiang/UI-Design-Build-Automation#5]

**Comment by hoanglonginthehus** [comment]
By using DOM XML Parser, I can convert .xml but data may be not cleaned. They have a bug which has a string "#text" when using method getTextContent() in Node class so contents were not as expected.

**Comment by lanhtruonggiang-k63a5** [comment]
Maybe try to use the algorithm to skip that part

**Comment by hoanglonginthehus** [comment]
Clear!

**Comment by hoanglonginthehus** [comment]
Done.
