### ISSUE TITLE
Other ways to convert data from wireframe to html?

### ISSUE THREAD

**Issue by lanhtruonggiang-k63a5** [lanhtruonggiang/UI-Design-Build-Automation#7]

**Comment by hoanglonginthehus** [comment]
Is there any other ways to convert wireframe data to .html file for web apps?

**Comment by lanhtruonggiang-k63a5** [comment]
I found this
https://sketch2code.azurewebsites.net/generated-html/65784686-4fd6-4874-bbcb-c3257ecdae73

**Comment by hoanglonginthehus** [comment]
WOW :O
